require("prrockzed.plugin_config.nvimtree")
require("prrockzed.plugin_config.lualine")
require("prrockzed.plugin_config.barbar")
require("prrockzed.plugin_config.gitsigns")
require("prrockzed.plugin_config.telescope")
require("prrockzed.plugin_config.whichkey")
require("prrockzed.plugin_config.toggleterm")
require("prrockzed.plugin_config.comment")
