require("prrockzed.snippets.tex.delimiters")
require("prrockzed.snippets.tex.environment")
require("prrockzed.snippets.tex.font")
require("prrockzed.snippets.tex.greek")
require("prrockzed.snippets.tex.math")
